import numpy as np
a=np.array([1,2,3,4,5])
print("a:",a)
sum=np.sum(a)
print("sum:",sum)
product=np.prod(a)
print("product:",product)
mean=np.mean(a)
print("mean:",mean)
standard_deviation=np.std(a)
print("standard_deviation:",standard_deviation)
variance=np.var(a)
print ("variance:",variance)
minimum=np.min(a)
print("minimum:",minimum)
maximum=np.max(a)
print ("maximum:",maximum)
minimum_index=np.argmin(a)
print("minimum_index:",minimum_index)
maximum_index=np.argmax(a)
print("maiximum_index:",maximum_index)
median=np.median(a)
print("median:",median)
      
      
